#ifndef OSFX_BUILD_CONFIG_H
#define OSFX_BUILD_CONFIG_H

/* Auto-generated from Config.json. */
/* Optional user overrides should be placed in osfx_user_config.h. */
#include "osfx_user_config.h"

#ifndef OSFX_ENABLE_FILE_IO
#define OSFX_ENABLE_FILE_IO 1
#endif
#ifndef OSFX_ENABLE_CLI
#define OSFX_ENABLE_CLI 1
#endif

#ifndef OSFX_CFG_PLUGIN_TRANSPORT
#define OSFX_CFG_PLUGIN_TRANSPORT 1
#endif
#ifndef OSFX_CFG_PLUGIN_TEST_PLUGIN
#define OSFX_CFG_PLUGIN_TEST_PLUGIN 1
#endif
#ifndef OSFX_CFG_PLUGIN_PORT_FORWARDER
#define OSFX_CFG_PLUGIN_PORT_FORWARDER 1
#endif

#ifndef OSFX_CFG_AUTOLOAD_TRANSPORT
#define OSFX_CFG_AUTOLOAD_TRANSPORT 1
#endif
#ifndef OSFX_CFG_AUTOLOAD_TEST_PLUGIN
#define OSFX_CFG_AUTOLOAD_TEST_PLUGIN 1
#endif
#ifndef OSFX_CFG_AUTOLOAD_PORT_FORWARDER
#define OSFX_CFG_AUTOLOAD_PORT_FORWARDER 1
#endif

#ifndef OSFX_CFG_PAYLOAD_DEVICE_ID
#define OSFX_CFG_PAYLOAD_DEVICE_ID 1
#endif
#ifndef OSFX_CFG_PAYLOAD_DEVICE_STATUS
#define OSFX_CFG_PAYLOAD_DEVICE_STATUS 1
#endif
#ifndef OSFX_CFG_PAYLOAD_TIMESTAMP
#define OSFX_CFG_PAYLOAD_TIMESTAMP 1
#endif
#ifndef OSFX_CFG_PAYLOAD_SUB_TEMPLATE_ID
#define OSFX_CFG_PAYLOAD_SUB_TEMPLATE_ID 1
#endif
#ifndef OSFX_CFG_PAYLOAD_SENSOR_ID
#define OSFX_CFG_PAYLOAD_SENSOR_ID 1
#endif
#ifndef OSFX_CFG_PAYLOAD_SENSOR_STATUS
#define OSFX_CFG_PAYLOAD_SENSOR_STATUS 1
#endif
#ifndef OSFX_CFG_PAYLOAD_PHYSICAL_ATTRIBUTE
#define OSFX_CFG_PAYLOAD_PHYSICAL_ATTRIBUTE 0
#endif
#ifndef OSFX_CFG_PAYLOAD_NORMALIZED_VALUE
#define OSFX_CFG_PAYLOAD_NORMALIZED_VALUE 1
#endif
#ifndef OSFX_CFG_PAYLOAD_GEOHASH_ID
#define OSFX_CFG_PAYLOAD_GEOHASH_ID 0
#endif
#ifndef OSFX_CFG_PAYLOAD_SUPPLEMENTARY_MESSAGE
#define OSFX_CFG_PAYLOAD_SUPPLEMENTARY_MESSAGE 1
#endif
#ifndef OSFX_CFG_PAYLOAD_RESOURCE_URL
#define OSFX_CFG_PAYLOAD_RESOURCE_URL 0
#endif

#ifndef OSFX_CFG_MULTI_SENSOR_BODY_CAP
#define OSFX_CFG_MULTI_SENSOR_BODY_CAP 4096
#endif

/*
 * When enabled, multi-sensor encode/decode uses static scratch buffers
 * instead of large stack allocations.
 */
#ifndef OSFX_CFG_MULTI_SENSOR_STATIC_SCRATCH
#if defined(ARDUINO) || defined(ESP32) || defined(ARDUINO_ARCH_ESP32) || defined(ARDUINO_ARCH_RP2040) || defined(ARDUINO_ARCH_MBED_RP2040)
#define OSFX_CFG_MULTI_SENSOR_STATIC_SCRATCH 1
#else
#define OSFX_CFG_MULTI_SENSOR_STATIC_SCRATCH 0
#endif
#endif

#endif
